### ISSUE TITLE
MicroPython backend crashing on get_editor_calltip

### ISSUE THREAD

**Issue by puppet13th** [thonny/thonny#2472]
sometimes thonny shell crashed when i coding in thonny editor.just updated to thonny 4.0.1.the issue exist since thonny 4.0.0.
OS : Windows 10 21H2 x64
```
>>> PROBLEM IN THONNY'S BACK-END: Exception while handling 'get_editor_calltip' (AttributeError: 'CompiledModule' object has no attribute 'non_stub_value_set').
You may need to press "Stop/Restart" or hard-reset your MicroPython device and try again.

See Thonny's backend.log for more info.

Process ended with exit code 1.
```
```
>>> 
Process ended with exit code 3221225725.
```

**Comment by aivarannamaa** [comment]
Thank you for the report!

Have you found a way for consistently reproducing this error?

**Comment by puppet13th** [comment]
it just happen randomly, the shortest interval is about 10 minutes.i have not tried to restart thonny when it happen.

**Comment by aivarannamaa** [comment]
If it happens again, then please send me the backend.log (Tools => Open Thonny data folder), before starting the backend again.

**Comment by puppet13th** [comment]
look like there is fault in frontend, please check.
```
>>> 
Process ended with exit code 3221225725.
```

[frontend_faults.log](https://github.com/thonny/thonny/files/10516868/frontend_faults.log)
[backend.log](https://github.com/thonny/thonny/files/10516870/backend.log)

**Comment by aivarannamaa** [comment]
Thanks! This is good information. It looks like the `jedi` library has problem in it. I'll investigate this.

**Comment by Flipje1955** [comment]
have the same issue recurrently on one of my W10 PC's. Log files available from the crash of this evening, can share if you wish. 
Typically the problem disappears for some time (hrs) after a restart of (at least) Thonny. 
- The suggestion above (deselect restart intepreter before running a script) does not appear to influence the behavior. Thonny 4.0.1 is used in both environments.
- For some time I thought it was related to the version of MP is am using but tonight I used the official 1.19.1 version (and have not seen any mentioning of this issue by others);
- use various different rp2040 boards (but cannot relate the issue to a specific one so appears to be related to the backend.
Problem is easy to solve (start/stop backend), still doing only sw development, so no big deal. 

Should you have a solution ...
thx !

**Comment by aivarannamaa** [comment]
@Flipje1955, the logs would be helpful -- please post the backend.log!

**Comment by Flipje1955** [comment]
appreciate your efforts ! Hereby, per your request. Let me know if and what you may need further.
[backend.log](https://github.com/thonny/thonny/files/10713463/backend.log)
[frontend_faults.log](https://github.com/thonny/thonny/files/10713464/frontend_faults.log)

**Comment by Flipje1955** [comment]
just posted them.
Best regards,

Op vr 10 feb. 2023 om 16:53 schreef Aivar Annamaa ***@***.***

**Comment by aivarannamaa** [comment]
@Flipje1955, can you please check, which `jedi` version are you using (Tools => Manage plug-ins)?

**Comment by Flipje1955** [comment]
[image: image.png]

per your request...

Op zo 12 feb. 2023 om 14:00 schreef Aivar Annamaa ***@***.***

**Comment by Flipje1955** [comment]
![Jedi Screenshot 2023-02-12 192803](https://user-images.githubusercontent.com/113593893/218329880-abd0dadc-1552-4e9d-96cc-c9376ecbc7fa.png)

included here again as attached file as the image.png may not be accessible / readable.

**Comment by aivarannamaa** [comment]
It looks like the risk of stack overflow is not easy to fix in jedi: https://github.com/davidhalter/jedi/issues/1902

**Comment by Flipje1955** [comment]
appreciate your continued attention to the matter; it continues to pop-up (but then, there are worst things in life than this issue). Thank you !

**Comment by puppet13th** [comment]
@aivarannamaa i was able to reproduce "exit code 3221225725" with these code :
```
number_list = []
some_list.append( 1 )
some_list.append( 2 )
some_list.append( 3 )
```
the error will occurred when typing "some_list." in the editor

```
MicroPython v1.20.0 on 2023-05-01; LOLIN S3 with ESP32S3

Type "help()" for more information.

>>> 
Process ended with exit code 3221225725.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

MPY: soft reboot
MicroPython v1.20.0 on 2023-05-01; LOLIN S3 with ESP32S3

Type "help()" for more information.

>>> 
Process ended with exit code 3221225725.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

MPY: soft reboot
MicroPython v1.20.0 on 2023-05-01; LOLIN S3 with ESP32S3

Type "help()" for more information.

>>> 
Process ended with exit code 3221225725.
```

[frontend_faults.log](https://github.com/thonny/thonny/files/11812249/frontend_faults.log)
[backend.log](https://github.com/thonny/thonny/files/11812250/backend.log)

currently using thonny 4.1.1

**Comment by Flipje1955** [comment]
interesting; the error does not occur when I try your code (using:
MicroPython v1.20.0-162-gd080d427e on 2023-06-06; Raspberry Pi Pico with
RP2040). It gives an error as some_list is not defined.

However, using the same listed MP version, there are moments like yesterday
when the 3221225725 error occurs within say 2 minutes of each other. A
reset of the board, a complete restart of the Thonny environment improves
the situation up to the point that there are days that it does not not
present itself at all. Cannot correlate the exit code to anything specific
I am doing in Thonny.

Using Thonny 4.0.2 on different W10 PC's. Good to see there is a Thonny
4.1.1; will install that soonest.

Thanks + wbr,

Op wo 21 jun 2023 om 06:37 schreef Rinaldi Jandrinata <
***@***.***>:

**Comment by aivarannamaa** [comment]
Thank you for the import! I'll attempt to reproduce this later.

**Comment by Flipje1955** [comment]
Just fyi: I upgraded Thonny to 4.1.1 and did some editing on my project
this evening and after say an hour, Thonny aborted with the famous "Process
ended with exit code 3221225725".

Wbr, Rob



Op za 24 jun 2023 om 09:50 schreef Aivar Annamaa ***@***.***>:

**Comment by HabibMCS** [comment]
import utime
import s3lcd
import tft_config
import font as font
from machine import reset_cause
tft = tft_config.config( 1,0)
def showscrolltext(char1 , fg = s3lcd.WHITE, bg = s3lcd.RED, pady=60, xs = -1, ys = 0, duration = 40):  
    try:
        tft_config.config( 1,0,backlight = 1)
        tft.init()
        curr = utime.time()
        tft.fill(bg)
        height = tft.height()
        width = tft.width()
        line = height - font.HEIGHT
        while utime.time() - curr < duration:
            for c in char1:
              tft.write(font,c,width - font.WIDTH*2,line-pady,fg,bg,)
              for _ in range(font.HEIGHT // 2):
                    tft.scroll(xs, ys)
                    tft.show()
            utime.sleep(3)
        if reset_cause():
            print(reset_cause())

    finally:
        tft_config.deinit(tft, display_off = True)
        print("scroll completed")
showscrolltext(' Hey its test for display 7809', duration = 5 )
utime.sleep(5)
showscrolltext(' Hey its test for display 7809', duration = 5 )


when the function is called second time the esp32s3 t display crashes.  I don't know whether to put the issue here. I would appreciate if someone helps on this. Thanks in advance

**Comment by HabibMCS** [comment]
> ```
> 
> import utime
> import s3lcd
> import tft_config
> import font as font
> from machine import reset_cause
> tft = tft_config.config( 1,0)
> def showscrolltext(char1 , fg = s3lcd.WHITE, bg = s3lcd.RED, pady=60, xs = -1, ys = 0, duration = 40):  
>     try:
>         tft_config.config( 1,0,backlight = 1)
>         tft.init()
>         curr = utime.time()
>         tft.fill(bg)
>         height = tft.height()
>         width = tft.width()
>         line = height - font.HEIGHT
>         while utime.time() - curr < duration:
>             for c in char1:
>               tft.write(font,c,width - font.WIDTH*2,line-pady,fg,bg,)
>               for _ in range(font.HEIGHT // 2):
>                     tft.scroll(xs, ys)
>                     tft.show()
>             utime.sleep(3)
>     finally:
>         tft_config.deinit(tft, display_off = True)
>         print("scroll completed")
> showscrolltext(' Hey its test for display 7809', duration = 5 )
> utime.sleep(5)
> showscrolltext(' Hey its test for display 7809', duration = 5 )
> ```
> 
> when the function is called second time the esp32s3 t display crashes. I don't know whether to put the issue here. I would appreciate if someone helps on this. Thanks in advance

It was solved, when I called the tft instance "tft = tft_config.config( 1,0) " within the function too

**Comment by aivarannamaa** [comment]
I now removed some hacks I used together with the Jedi library. Please try https://github.com/thonny/thonny/releases/tag/v4.1.2 and reopen this issue if these errors still occur.

**Comment by Flipje1955** [comment]
thank you for your efforts !

have installed it and will report any results.

Rob

Op za 12 aug 2023 om 23:06 schreef Aivar Annamaa ***@***.***>:

**Comment by puppet13th** [comment]
@aivarannamaa i have updated to thonny version 4.1.2 and try to reproduce the issue. i can confirm that the issue fixed in thonny 4.1.2. thank you very much for your hard work.

**Comment by Flipje1955** [comment]
Running the upgrade since its release and it is perfectly stable. Thanks
also from my side.
Wbr

Op za 19 aug. 2023 09:14 schreef Rinaldi Jandrinata <
***@***.***>:

**Comment by adrianblakey** [comment]
Please could you allow Thonny to copy all file types from a local directory to the board? I want to transfer the files in lib - the copy fails trying to copy mpy files.
